### PR TITLE
Support for Multiple Payloads

### PR DESCRIPTION
**Pull request by wdahlenburg**
Added the ability to use multiple payloads. This is done by the user passing in a list instead of just one parameter. Passing in a single payload still works. 

The occurrences of the payload in the UI are now joined together with the "/" character. This could definitely be improved upon.

I'd like to be able to get the table to size dynamically depending on the number of payloads.

### CODE REVIEW

**Comment by albinowax** [comment]
Nice work, looks well thought out and I'm sure a lot of people will appreciate it. Yeah, fixing up the table could be a little fiddly as it'll require refactoring RequestTableModel a bit. Do you want to wait until that's  done before merging or go ahead as-is?

**Comment by albinowax** [comment]
Ah, looks like this currently breaks attempts to queue requests with no payloads.

I really need to make some tests.

**Comment by wdahlenburg** [comment]
I worked on handling the empty test cases. I simplified the template and payload criteria. Let me know if this is stricter than you were looking for.

The second commit should cover:

1. Previous single payload
2. Lists for multiple payloads
3. No value or None
4. Empty list

**Comment by wdahlenburg** [comment]
I don't mind waiting on the table. Your call.

**Pull request merged**
